#!/usr/bin/env python3
"""
HxMod v1.0 - Executable wrapper for hash_identifier
Simply redirects to the main application
"""

import sys
import os

# Get the directory where this script is located
script_dir = os.path.dirname(os.path.abspath(__file__))

# Import and run the main application
sys.path.insert(0, script_dir)

from hash_identifier import main

if __name__ == '__main__':
    main()
